# Generated by Django 4.0.6 on 2022-09-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosinscritos',
            options={'ordering': ['id'], 'verbose_name': 'Usuario Inscrito', 'verbose_name_plural': 'Usuarios Inscritos'},
        ),
    ]
